### ISSUE TITLE
Bible Study/RV

### ISSUE THREAD

**Issue by kerrcady** [leviFrosty/jw-time#116]
It would be nice to put when we have a Bible Study or RV on each day we work.

**Comment by leviFrosty** [comment]
@kerrcady 

Thanks for writing in.

There might be a misunderstanding here. 

- Time is tracked per day
- Studies are tracked per contact

Since the branch does not request we keep track of studies on a day-to-day basis, your study total is calculated for the entire month.

To add a study to your report, **count a 'conversation' with a contact as "Conducted Bible Study"**. This will indicate to JW Time that you now have 1 study. Multiple conversations can be counted as "Conducted Bible Study" for the same contact in the same month. The program is smart enough to not count multiple 'sessions' as more than 1 study per month per contact.

Your study count will **only increase when you have an active study for an individual contact in a given month**.

To add more studies, you must add **different contacts** and report a new conversation as a study for the current month.

I hope this clears things up. Let me know if you have any questions.

Best,
Levi
