### ISSUE TITLE
[BUG] Failed to Open URL

### ISSUE THREAD

**Issue by caiovfelipe** [leviFrosty/jw-time#117]
**Describe the bug**
Hello! When I try to share the service report to Hourglass, I get the error: "Failed to Open URL. Please verify you have a valid aplication for the provided link. This erros tipically means you do not have a browser..."

**To Reproduce**
Click on Share service report icon in the home page, and select Hourglass..

**Screenshots**
![Screenshot_20240516-205344_JW Time](https://github.com/leviFrosty/jw-time/assets/75501510/163a5308-b29d-429f-8475-53cbb55d5ff0)

**Smartphone:**

- Device: [Samsung A30s]
- OS: [Android version: 11. One UI version: 3.1]
- Version [1.27.0]

**Additional context**
I also tried in another device (Android btw), but I got the same error. I have 3 browsers i n my phone.

Oh, and it's an amazing app brother, congratulations

**Comment by leviFrosty** [comment]
@caiovfelipe 

Thanks for writing in.

I will look into reproducing this on my end and let you know what I find.

I'm glad you're enjoying the app and hope things are well for you :)

Best,
Levi

**Comment by leviFrosty** [comment]
@caiovfelipe

I believe this issue is related to Android 11. Are you able to update your device to Android 12?

Please let me know if this is possible - if not, I might be able to come up with a resolution - although I can't guarantee it.

Best,
Levi

**Comment by caiovfelipe** [comment]
@leviFrosty 
Hey Levi. Unfortunately I'm not able to update it. My phone no longer supports updates

**Comment by leviFrosty** [comment]
I believe ed1117c66bbd4f40c1449219f9b9247025fcd3ee will resolve your issue.

I have pushed this change via Expo update. This means the update is available immediately, you do not need to download it via the Play Store.

There are two ways to update your app:
1. Open app > settings > check for update
2. Leave your app open for about 1 minute, then force close it and open it back up.

Either way, the app should update. After updating, please check to see if the issue is resolved.

Please let me know what you find.

Best,
Levi

**Comment by caiovfelipe** [comment]
It worked! Thank you so much. It'll help me a lot
Sorry for the delay in responding.

Thank you for this amazing app.

Greetings from Brazil
Best,
Caio

**Comment by caiovfelipe** [comment]
It worked! Thank you so much. It'll help me a lot
Sorry for the delay in responding.

Thank you for this amazing app.

Greetings from Brazil
Best,
Caio
