### ISSUE TITLE
[FEATURE] Account Log In Feature

### ISSUE THREAD

**Issue by Myst3r-E** [leviFrosty/jw-time#120]
Hello, I just recently downloaded your app (JW Time) and I love how functional it is as well as how amazing it looks. However, I have been downloading a lot of ministry apps in search for one that has the ability to create an account. That way I can sign into more than one device such as my IPad for e.x. or my computer, both of which I use quite frequently for ministry activities so it would be really nice to be able to start/stop time, add/remove a R.V. or just check up on my stats using another device than just my phone.

I do want to say, thank you sooo much for the hard work you have put into making this app and making our lives a little bit easier lol. And even without the ability to create and log into an account, the app is still fantastic and totally worth using. 

Thank you again : )

**Comment by leviFrosty** [comment]
Hi @Myst3r-E!

Thanks for taking the time to write in an issue.

Due to the following design decisions:
- International Support
- Offline-first priority (Although possible with a database, it can lead to issues for users who primarily live in very bad signal areas of the world)
- Security and data privacy concerns with user data stored in servers
- Low cost (I do not make money from JW Time and hosting databases can get expensive). I also do not want to make JW Time cost money to use.

Technically there would be ways to get around all of these points and still use cloud storage, but I believe that it is not in the scope of what I wish to do with this app.

I hope you understand where my reasoning and compromises comes from.

For you, I would suggest in the meantime to pick a 'primary' device, and use this as your means to keep your records. It's not ideal, but I believe this is your best option.

An aside, JW Time automatically reminds you to create backups so you do not lose your data. You can also optionally adjust your reminder preferences in the settings.

And just for the record: I may walk back my decision on this. For now, however, this is not something that is likely to change.

I hope you continue to use JW Time and enjoy the coming features. If you find value from the app, please consider leaving a review and sharing with your friends.

Best,
Levi
