### ISSUE TITLE
[FEATURE] Monthly planner

### ISSUE THREAD

**Issue by marlonsabala** [leviFrosty/jw-time#96]
Hi there. You have done such a great job with this app thus far. Way prettier and more intuitive than anything out there. I have been looking for a “my time” replacement for years. Well done. 

It would be cool to have a planner calendar. Something that would allows us to pencil in regular slots for different days of the week. With that data, it could easily calculate how much would be expected and update as the month goes by and we add the “actual” figures. 

What do you think?

greag job anyway. Thanks a bunch

**Comment by leviFrosty** [comment]
Hi @marlonsabala , thanks for writing in. I appreciate the kind words and am glad you're enjoying the app.

A planner calendar is something that I've considered implementing, but I want to make it the best possible planner calendar that I can. It should also be extremely easy to use.

I will let you know when I begin on this. It may take some time because I am currently very busy in real life.

If you have any specific screenshots/suggestions/things you like - reply here with those and I might use them as a reference when I begin developing the feature.

Thanks
Levi

**Comment by marlonsabala** [comment]
How about this Levi

https://share.icloud.com/photos/0f4kCqL9cYaWs8HI0xnJyNlYQ

Marlon Sabala

**Comment by leviFrosty** [comment]
@marlonsabala Hi!

Fantastic news! This feature has been added with fe7be58a6c48d2563d2ef6ee9460f6ad6d95c684

Thanks for taking the time to write in a feature request.
Please be on the lookout for this update in the coming days! I will be closing this ticket now.

When you see the feature on your app - and if this new feature is everything you could have hoped for, please leave a review and share JW Time with your friends :)

Best,
Levi

**Comment by marlonsabala** [comment]
That’s great Levi. You work fast.

I wanted to ask you. What is you hourly rate?

We run an e-learning business, and have been working on an app, but our current solution falls very short of the ideal.

Thanks

**Comment by leviFrosty** [comment]
@marlonsabala 

I'd be interested to hear more about this but this thread is public.

Please email, me so we can have a private conversation: levi@leviwilkerson.com

You can just say "hi" and I'll send you an email back with a meeting invite.

Thank you!
Levi
